# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ciandttalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_07B963E371794CB28621D858B05C46E6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_669592EFD9F64854869DC3C4B7A093B0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_88E13A0974A04587982C84EE7638CB3C }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Capture App Service name
        id: capture-app-service-name
        run: echo "APP_SERVICE_NAME=$(terraform output -raw app_service_name)" >> $GITHUB_OUTPUT
        
  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install

      - name: 'Deploy to Azure Web App'
        env: 
          APP_SERVICE_NAME : ${{ steps.capture-app-service-name.outputs.APP_SERVICE_NAME }} 
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: $APP_SERVICE_NAME
          slot-name: 'Production'
          package: .
          
